export enum Role {
  DOCTOR = 'DOCTOR',
  MSDHO = 'MSDHO',
  SECTION_OFFICER = 'SECTION_OFFICER',
  DEPUTY_SECRETARY = 'DEPUTY_SECRETARY',
  ADDITIONAL_SECRETARY = 'ADDITIONAL_SECRETARY',
  SPECIAL_SECRETARY = 'SPECIAL_SECRETARY',
  SECRETARY = 'SECRETARY',
  MINISTER = 'MINISTER',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export const REQUESTER_ROLES = [Role.DOCTOR, Role.MSDHO] as const;
export const INTERNAL_COMMENT_ROLES = [
  Role.MSDHO, Role.SECTION_OFFICER, Role.DEPUTY_SECRETARY, Role.ADDITIONAL_SECRETARY,
  Role.SPECIAL_SECRETARY, Role.SECRETARY, Role.MINISTER, Role.SUPER_ADMIN,
] as const;
