import { BadRequestException } from '@nestjs/common'; import { BaseLeaveEngine } from './base.engine'; import { LeaveContext, LeaveType, PolicyResult } from '../leave.types';
export class MaternityEngine extends BaseLeaveEngine { supports(t:string){return t===LeaveType.MATERNITY} evaluate(c:LeaveContext){const d=this.days(c); if(c.gender!=='Female')throw new BadRequestException('Maternity leave is applicable to female employees only'); if(d>90)throw new BadRequestException('Maternity leave cannot exceed 90 days'); if(c.previousApprovedCount>=3)throw new BadRequestException('Maximum 3 maternity leaves are allowed during service'); return {requestedDays:d,balanceDeduction:0,metadata:{serviceLimit:3,medicalCertificateOptional:true}};} }
export class PaternityEngine extends BaseLeaveEngine { supports(t:string){return t===LeaveType.PATERNITY} evaluate(c:LeaveContext){const d=this.days(c); if(c.gender!=='Male')throw new BadRequestException('Paternity leave is applicable to male employees only'); if(d>7)throw new BadRequestException('Paternity leave cannot exceed 7 days'); if(c.previousApprovedCount>=2)throw new BadRequestException('Maximum 2 paternity leaves are allowed during service'); return {requestedDays:d,balanceDeduction:0,metadata:{serviceLimit:2}};} }
export class CasualEngine extends BaseLeaveEngine { supports(t:string){return t===LeaveType.CASUAL} evaluate(c:LeaveContext){const d=this.days(c); if(c.startDate.getMonth()!==c.endDate.getMonth()||c.startDate.getFullYear()!==c.endDate.getFullYear())throw new BadRequestException('Casual leave must fall within one calendar month'); if(d+c.monthlyCasualUsed>2)throw new BadRequestException('No casual leaves remaining for this month'); return {requestedDays:d,balanceDeduction:0,metadata:{monthlyLimit:2,carryForward:false}};} }
export class EarnedFullEngine extends BaseLeaveEngine { supports(t:string){return t===LeaveType.EARNED_FULL} evaluate(c:LeaveContext){const d=this.days(c); if(this.yearsOfService(c)<1)throw new BadRequestException('Earned leave requires at least 12 months of service'); if(c.balance<d)throw new BadRequestException('Insufficient leave balance'); return {requestedDays:d,balanceDeduction:d};} }
export class HalfPayEngine extends BaseLeaveEngine { supports(t:string){return t===LeaveType.HALF_PAY} evaluate(c:LeaveContext){const d=this.days(c),x=Math.ceil(d/2); if(c.balance<x)throw new BadRequestException('Insufficient leave balance'); return {requestedDays:d,balanceDeduction:x};} }
export class EolEngine extends BaseLeaveEngine { supports(t:string){return t===LeaveType.EOL} evaluate(c:LeaveContext){const d=this.days(c); this.requireDoc(c,'Written Request Document'); return {requestedDays:d,balanceDeduction:0,requiredDocument:'Written Request Document'};} }
export class ExPakistanEngine extends BaseLeaveEngine { supports(t:string){return [LeaveType.EX_PAK_FULL,LeaveType.EX_PAK_HALF,LeaveType.EX_PAK_EOL].includes(t as LeaveType)} evaluate(c:LeaveContext){const d=this.days(c);this.requireDoc(c,'Government Permission Letter');const x=c.type===LeaveType.EX_PAK_FULL?d:c.type===LeaveType.EX_PAK_HALF?Math.ceil(d/2):0;if(c.balance<x)throw new BadRequestException('Insufficient leave balance');return {requestedDays:d,balanceDeduction:x,requiredDocument:'Government Permission Letter'};} }
export class SpecialMedicalEngine extends BaseLeaveEngine { supports(t:string){return [LeaveType.SPECIAL_ACCIDENT,LeaveType.MEDICAL_LONG].includes(t as LeaveType)} evaluate(c:LeaveContext){const d=this.days(c);this.requireDoc(c,'Medical Certificate');return {requestedDays:d,balanceDeduction:0,requiredDocument:'Medical Certificate'};} }
export class QuarantineEngine extends BaseLeaveEngine { supports(t:string){return t===LeaveType.SPECIAL_QUARANTINE} evaluate(c:LeaveContext){const d=this.days(c);this.requireDoc(c,'Quarantine Order');return {requestedDays:d,balanceDeduction:0,requiredDocument:'Quarantine Order'};} }
export class LprEngine extends BaseLeaveEngine { supports(t:string){return t===LeaveType.LPR} evaluate(c:LeaveContext){const d=this.days(c),age=this.ageAtStart(c);if(age<59||age>=60)throw new BadRequestException('LPR is selectable only from age 59 until before age 60');if(d>365)throw new BadRequestException('LPR cannot exceed 365 days');if(c.balance<d)throw new BadRequestException('Insufficient leave balance for requested LPR');return {requestedDays:d,balanceDeduction:d,metadata:{ageAtStart:age}};} }
export class StudyEngine extends BaseLeaveEngine { supports(t:string){return [LeaveType.STUDY_FULL,LeaveType.STUDY_HALF,LeaveType.STUDY_EOL].includes(t as LeaveType)} evaluate(c:LeaveContext){const d=this.days(c);if(this.yearsOfService(c)<5)throw new BadRequestException('Study leave requires at least 5 years of service');if(d>730)throw new BadRequestException('Study leave cannot exceed 2 years');this.requireDoc(c,'Admission Letter');const x=c.type===LeaveType.STUDY_FULL?d:c.type===LeaveType.STUDY_HALF?Math.ceil(d/2):0;const requiredAvailable=c.type===LeaveType.STUDY_EOL?d:x;if(c.balance<requiredAvailable)throw new BadRequestException('Insufficient leave balance');return {requestedDays:d,balanceDeduction:x,requiredDocument:'Admission Letter',metadata:{maximumDays:730,requiredAvailableBalance:requiredAvailable}};} }
export const POLICY_ENGINES=[MaternityEngine,PaternityEngine,CasualEngine,EarnedFullEngine,HalfPayEngine,EolEngine,ExPakistanEngine,SpecialMedicalEngine,QuarantineEngine,LprEngine,StudyEngine];
